-- Seeds for all production database tables

-- password: $2b$10$zUr5GSoayQGyHxrhRU512ekcmmdQe0dcI7v3BJlbukUz7U6IOVQim
-- 123:      $2b$10$WMtxQHMdAIcArSAe8B.dPu3FJ56M2.MenoSGja8Xx/6PGkDcFgrzG

-- Sandbox is automatically generated by the server

-- INSERT INTO sessions (session_key, name) VALUES
--   ('sandbox', 'Sandbox')
-- ;
