CREATE USER estimatron2020_development WITH NOSUPERUSER PASSWORD 'estimatron2020_development';
CREATE DATABASE estimatron2020_development OWNER estimatron2020_development;
GRANT ALL ON DATABASE estimatron2020_development TO estimatron2020_development;
